# Target operating system
SET (CMAKE_SYSTEM_NAME Windows)
SET (TOOLCHAIN_PREFIX x86_64-w64-mingw32)

# Compiler selection
SET (CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-gcc)
SET (CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)

SET (CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
SET (CMAKE_SYSROOT ${TOOLCHAIN_ROOT})

SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Configure options for the build type
SET (CMAKE_CXX_FLAGS_INIT                "-Wall -m64")
SET (CMAKE_CXX_FLAGS_DEBUG_INIT          "-O0 -g -D_ENABLE_LOGGING")
SET (CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE_INIT        "-O2 -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
